language: python
python:
  - "3.6"
services:
  - postgresql
before_script:
  - psql -c 'create database everyday_test;' -U postgres
install:
  - pip install -r everyday/requirements.txt
script:
  - python manage.py test
env:
  - SECRET_KEY="super_secret_key"
