language: python
services:
  - postgresql
before_script:
  - psql -c 'create database everyday_test;' -U postgres
python:
  - "3.6"
install:
  - pip install -r everyday/requirements.txt
script:
  - python manage.py test

matrix:
  include:
    - language: node_js
      node_js:
        - "node"
      install:
        - npm install
      script:
        - npm run lint

env:
  - SECRET_KEY="super_secret_key"
