language: python
services:
  - postgresql
before_script:
  - psql -c 'create database eachday_test;' -U postgres
python:
  - "3.6"
  - "2.7"
install:
  - pip install -r eachday/requirements.txt
script:
  - python manage.py test

matrix:
  include:
    - language: node_js
      node_js:
        - "node"
      cache: yarn
      install: yarn
      script:
        - npm run lint
        - npm test

env:
  - SECRET_KEY="super_secret_key"
