export const AUTH_USER = 'auth_user'
export const UNAUTH_USER = 'unauth_user'
export const AUTH_ERROR = 'auth_error'
export const FORGOT_PASSWORD_REQUEST = 'forgot_password_request'
export const RESET_PASSWORD_REQUEST = 'reset_password_request'
export const LOAD_ENTRIES = 'load_entries'
