"""empty message

Revision ID: 8c5591beef85
Revises: 
Create Date: 2017-05-19 09:58:50.364036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5591beef85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('date', sa.Date(), nullable=False))
    op.create_unique_constraint(None, 'entry', ['user_id', 'date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entry', type_='unique')
    op.drop_column('entry', 'date')
    # ### end Alembic commands ###
